### ISSUE TITLE
Failed login testing

### ISSUE THREAD

**Issue by gauravVanvari** [watir/nerodia#10]
I am trying to test an application using Nerodia, and I am having a hard time to figure out - how to log/capture a failed login attempt.

A toaster pops up for both success and failure. Currently the program captures screenshot for every attempt - both successful and failure. But I have to open the captured image to find if it was successful or not.

Logging in with wrong credentials is not an exception which I can catch using try/catch. Is there a way I can log the failure the same way as success ?

if I inspect Toaster’s HTML code, it disappears as soon as the Toaster disappears.

    def login(browser):

        username = browser.text_field(name='username')
        username.value = user_name
        password = browser.text_field(name='password')
        password.value = pass_key

        browser.button(name='submit').click()
        browser.screenshot.save('screenshot.png')

        logger.info('login successful')

**Comment by lmtierney** [comment]
Hi, issues are reserved for issues with the library itself. Please send questions to [the Nerodia-General mailing list](https://groups.google.com/forum/#!forum/nerodia-general) on Google Groups. or [join our slack channel](https://github.com/watir/nerodia#join-our-slack-channel)

**Comment by gauravVanvari** [comment]
I figured how to do it , I appologize

**Comment by joshmgrant** [comment]
That is perfectly ok! Definitely reach out on the seleniumhq slack under #nerodia or on the mailing list.
