### ISSUE TITLE
Setting headless to False still runs browser in headless

### ISSUE THREAD

**Issue by abotalov** [watir/nerodia#11]
## Expected Behavior -
Setting an option to False should lead to browser run in regular mode.

## Actual Behavior -
Creating a browser with `headless=False` option leads to browser being run in headless mode.
This is because code checks presence of option in the dictionary rather than value of it.
https://github.com/watir/nerodia/blob/4fc0af3442b39d6b62abd387011c5409da9ca2b1/nerodia/capabilities.py#L97

**Comment by lmtierney** [comment]
Why are you including the option if you don't want headless mode?

**Comment by abotalov** [comment]
Well, I had `headless=True` and thought it would be fine to change it to `False`.
