### ISSUE TITLE
Nerodia 0.12 isn't able to find element by attribute name with dashes

### ISSUE THREAD

**Issue by abotalov** [watir/nerodia#16]
## Meta -
Nerodia Version: 0.12
Selenium Version: 3.14.1

## Expected Behavior -
Nerodia is able to find element with custom attribute name that has dashes.

## Actual Behavior -
`browser.element(custom_attr="value").exists` should search for element with attribute name `custom-attr` but it searches for element with attribute `custom_attr`.

## Steps to reproduce -
```
import nerodia

nerodia.default_timeout = 3
br = nerodia.browser.Browser()
br.goto("https://fiddle.jshell.net/gdryL30q/show/")
iframe = br.iframe()
print iframe.element(custom_attr="value").exists
br.close()
```

**Comment by lmtierney** [comment]
So this is something that I had to make a design decision on, but I'm open for feedback. Previously, the code changed any attribute that had underscores to a dashed value which is what you are depending on. The problem with that is, you can't use custom attributes with underscores. So, if your attribute was actually `custom_attr` in the html, it'd be searching for `custom-attr` and it would not be found.

What you can do to get around that is to unpack a dictionary into your container:

    iframe.element(**{'custom_attr'='value'}).exists

I'm also thinking now that we should allow just a dictionary passed in so we don't have to unpack it:

    iframe.element({'custom_attr'='value'}).exists

Unfortunately in the previous logic, besides adding an extra wire call each time, there isn't a way to force looking for an underscore attribute to override default logic of converting `_` to `-`.

**Comment by lmtierney** [comment]
I should also note that I kept the functionality around for `data-` or `aria-` attributes

**Comment by abotalov** [comment]
Ruby also disallows dashes in attribute names. I think having the same behaviour as Watir makes more sense (https://github.com/watir/watir/blob/master/spec/watirspec/elements/div_spec.rb#L20). I thought a goal of the project was to be "a Python port of the Watir ruby gem".

Some other arguments for having same behaviour as Watir (i.e. replace `-` with `_`):
* Dash is replaced with underscore for data and aria attributes so replacing it everywhere would be more consistent
* Treating dashes in custom attribute names in special way also seems to be a feature in some js frameworks - https://www.polymer-project.org/3.0/docs/devguide/properties#property-name-mapping, https://stackoverflow.com/questions/14289459/html-element-attribute-names-with-hyphens-are-auto-converted-to-camelcase/14289581

> The problem with that is, you can't use custom attributes with underscores.

The counter-argument is the same as for dashes: elements with underscores can be found using dict with string keys - didn't check this but I would expect it should.

**Comment by lmtierney** [comment]
One solution could be:

- If passed in as a keyword i.e. `div(custom_attr='foo')` convert to dash
- If passed in via dictionary i.e. `div({'custom_attr='foo'})`, don't convert
Which would be done in the `_extract_selector` method https://github.com/watir/nerodia/blob/c03d03afa60f1ecf7e95f0c94d2cb89698f1b490/nerodia/container.py#L13

The only problem with this is if people want to create selectors with multiple keys in a dictionary and pass that to the container.

**Comment by lmtierney** [comment]
Another less-than-ideal solution would be to add a switch on the library. Either convert all or don't

`nerodia.underscores_to_dashes = False`

**Comment by lmtierney** [comment]
@abotalov as this was a breaking change, I am going to restore the functionality until I can come up with a better solution. Fixed with https://github.com/watir/nerodia/commit/2f2b9060ae7179c06531a9c3d58f0eebc4a8d44f and will be released in a patch release.

**Comment by abotalov** [comment]
> Where it matters, div(**{'custom_attribute': 'foo'} would get you the same locator as div(custom_attribute='foo').

I'm sorry for some exaggerations. I didn't realize that it's the case for some reason.

**Comment by lmtierney** [comment]
@abotalov `0.12.1` is released now and should restore this behavior.
