### ISSUE TITLE
How specify a regex in locator?

### ISSUE THREAD

**Issue by alteryx-sezell** [watir/nerodia#21]
I've used Watir before and found the ability to pass in a regex instead of a full name really helpful. Ruby has a regex object, you just pass that in as the value for name or class or whatever attribute you want to select on, but python does not have a regex object. So does nerodia support regex matching and if so, how I pass it into a container? I looked the examples and didn't see an example using a regex. Thanks for the information!

BTW, thanks for doing Watir for python! I love Watir, but my current project is using only python so I'm super excited to find this!

**Comment by lmtierney** [comment]
Hi @alteryx-sezell. Yes Nerodia does allow regex. You can compile a regex pattern using:

```
import compile

browser.div(text=re.compile(r'foo')
```

Or, as of [v0.13.0](https://github.com/watir/nerodia/releases/tag/v0.13.0), any string you pass that starts and ends with `/` gets converted to a regex locator. So the equivalent to above would be:

```
browser.div(text='/foo/')
```

**Comment by lmtierney** [comment]
If you have any issues, please feel free to find us on [Slack](https://github.com/watir/nerodia#join-our-slack-channel)

**Comment by alteryx-sezell** [comment]
Thanks, super helpful!
