### ISSUE TITLE
Iterate divs by class? 

### ISSUE THREAD

**Issue by dvwright** [watir/nerodia#23]
Hi, this is a question, not a bug. 

In watir one can iterate through elements such as:
```ruby
browser.divs(class: 'my_class').each do |e|
  puts e.text
end
```
How would one accomplish this in nerodia? 
e.g.
```python
for e in browser.divs(class_name = 'my_class'):
    puts e.text
```

Thank you

**Comment by lmtierney** [comment]
```
for e in browser.divs(class_name = 'my_class'):
    print(e.text)
```

In the future, please send questions to either our [support channel](https://github.com/watir/nerodia#support) or our [Slack](https://github.com/watir/nerodia#join-our-slack-channel). Issues are reserved for actual issues in the code.
