### ISSUE TITLE
Elements Collection issue.

### ISSUE THREAD

**Issue by SinxRofozoteron** [watir/nerodia#26]
## Meta -
Nerodia Version: 0.14.1
Selenium Version: 3.141.0
Browser Version:  85.0.4183.121

Hello here are two print statements:
`print(browser.span(class_name="foo"))` 
`print(len(browser.spans(class_name="foo")))`

## Expected Behavior -
supposed to return:
`#<Span: located: True; {'class_name': 'foo', 'tag_name': 'span'}>`
`2`

## Actual Behavior -
Returns:
`#<Span: located: False; {'class_name': 'foo', 'tag_name': 'span'}>`
`0`

## Steps to reproduce -
While trying to click on element it works:
`browser.span(class_name="foo").click()`
But when trying to print an element it returns `located: False`:
`print(browser.span(class_name="foo"))` 
When I'm trying to get all elements with given class name on a page it returns an empty collection.

**Comment by titusfortner** [comment]
This is the expected / desired behavior.
Watir / Nerodia allows you to define the element without locating it.
It will only locate it when you try to do something with it.

Not certain the correct Python for this, but in Ruby you *could do:
```ruby
element = browser.span(class_name="foo").tap(&:exists?)
elements = browser.spans(class_name="foo").select(&:exists?)
```

but again there's nothing valuable from just locating the elements. What are you actually trying to do or learn about the elements?

**Comment by SinxRofozoteron** [comment]
Thank you!!

**Comment by SinxRofozoteron** [comment]
I need to locate all the elements with specified id and extract text from them.

**Comment by titusfortner** [comment]
So, if you are verifying text, it could actually be more useful to do:

(Ruby example)
```ruby
browser.span(class_name: "foo", text: "validate this text").exists?
```
otherwise this would get you a list of text from matching elements
```ruby
browser.spans(class_name: "foo").map(&:text)
```

Let me know if you need help with the Python of it, easier to do Ruby off the top of my head. :-D
