### ISSUE TITLE
Dealing with 'for' attribute.

### ISSUE THREAD

**Issue by SinxRofozoteron** [watir/nerodia#28]
## Meta -
Nerodia Version: 0.14.1
Selenium Version: 3.141.0
Browser Version:
Browser Driver Version:
OS Version:

It's not an issue, it's more like a curiosity question:
There is a built in python function associated with word 'for', same as with 'class' attribute. For 'class' I can use 'class_name', is there a fix like that for 'for' attribute?

**Comment by lmtierney** [comment]
I'll refer to the documentation https://nerodia.readthedocs.io/en/latest/watir.html#locators

Basically the only way to do this with 'for' is something like this:

```
locator = {'for': 'spam', 'index': 1}
browser.div(**locator)
```
