### ISSUE TITLE
exists(), visible(), present() is not returning true instead returns bool value

### ISSUE THREAD

**Issue by anilreddy** [watir/nerodia#39]
## Meta -
Nerodia Version: 0.14.1
Selenium Version: 3.141.0
Browser Version: Chrome
Browser Driver Version: 89.0.4389.23
OS Version: Windows 10

## Expected Behavior -
It should return True or False and should continue execution
## Actual Behavior -
TypeError: 'bool' object is not callable
## Steps to reproduce -
```python
from nerodia.browser import Browser

browser = Browser(browser='chrome')
browser.goto('google.com')

search_input = browser.text_field(title='Search')
search_input.value = 'nerodia'
browser.button(value='Google Search').click()

if browser.h3(text='Nerodia - Wikipedia').exists():
    browser.h3(text='Nerodia - Wikipedia').click()
browser.close()
```
**Output:**
```python
   if browser.h3(text='Nerodia - Wikipedia').exists():  
TypeError: 'bool' object is not callable
```

**Comment by lmtierney** [comment]
They're all properties, they aren't callable as the error says. Call them without parenthesis

**Comment by anilreddy** [comment]
@lmtierney Thanks
